---

- name: "Unzip BRMS"
  unarchive:
    copy: no
    src: "{{software_repo}}/jboss-brms-6.2.0.GA-deployable-eap6.x.zip"
    dest: "/tmp"
    owner: "{{eap_service_user}}"
    group: "{{eap_service_user}}"
    creates: "{{eap_install_path}}/standalone/deployments/business-central.war"
  notify:
    - sync brms bin
  tags: [brms]

- set_fact:
    brms_host_ip: "{{hostvars[inventory_hostname]['ip']}}"

- name: sync brms bin
  synchronize:
    src: "/tmp/{{brms_deployable}}/bin/"
    dest: "{{eap_install_path}}/bin/"
  notify:
    - sync brms domain config
  delegate_to: "{{brms_host_ip}}"
  tags: [brms]

- name: sync brms domain config
  synchronize:
    src: "/tmp/{{brms_deployable}}/domain/configuration/"
    dest: "{{eap_install_path}}/domain/configuration/"
  notify:
    - sync brms standalone config
  delegate_to: "{{brms_host_ip}}"
  tags: [brms]

- name: sync brms standalone config
  synchronize:
    src: "/tmp/{{brms_deployable}}/standalone/configuration/"
    dest: "{{eap_install_path}}/standalone/configuration/"
  notify:
    - deploy business-central and kie
  delegate_to: "{{brms_host_ip}}"
  tags: [brms]

- name: deploy business-central and kie
  synchronize:
    src: "/tmp/{{brms_deployable}}/standalone/deployments/"
    dest: "{{eap_install_path}}/standalone/deployments/"
  delegate_to: "{{brms_host_ip}}"
  tags: [brms]

- name: "Create BRMS Users"
  shell: "{{eap_install_path}}/bin/add-user.sh -a -u {{item.key}} -p {{item.value.password}} -g {{item.value.roles}}"
  with_dict: "{{users}}"
  delegate_to: "{{brms_host_ip}}"
  tags: [brms]
